version: '3.6'
services:
  vue:
    container_name: vue
    build: .
    working_dir: /app
    command: 
      - /bin/sh
      - '-c'
      - 'yarn install && yarn run serve'
    ports:
      - '8080:8080'
    volumes:
      - './:/app'